services:
  - type: web
    name: spam-prediction-backend
    env: docker
    region: singapore # Optional: Choose a region close to you
    plan: free # Optional: Explicitly set free plan
    dockerContext: backend
    dockerfilePath: backend/Dockerfile
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 8000